### ISSUE TITLE
implement select() call

### ISSUE THREAD

**Issue by S4mw1s3** [tass-belgium/picotcp-bsd#1]

**Comment by danielinux** [comment]
First implementation available on 966bed9ccf987ea31bf681bf9fb7d8a7827f8f0e

**Comment by maximevince** [comment]
Work in progress: 966bed9

**Comment by maximevince** [comment]
Currently tested only on NoOS.
OS implementation need a global socket signal - no there yet..

**Comment by danielinux** [comment]
It works. closing..
